/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EnrollmentModal: typeof import('./components/EnrollmentModal.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    HeaderTable: typeof import('./components/HeaderTable.vue')['default']
    NoItemsTable: typeof import('./components/NoItemsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
